"""
============================================================
AoA IMPERSONATION CHALLENGE — Streamlit App
============================================================
Run with: python -m streamlit run aoa_challenge_app.py
Requires: challenge_data.npz (generated by extract_challenge_data.py)
"""

import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd

# ============================================================================
# PAGE CONFIG
# ============================================================================
st.set_page_config(
    page_title="AoA Impersonation Challenge",
    page_icon=None,
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
    /* ---- Background ---- */
    .stApp {
        background: linear-gradient(160deg, #0a0f2c 0%, #0d1f4a 40%, #0a2a3d 100%);
    }

    /* ---- Hero banner ---- */
    .hero {
        text-align: center;
        padding: 52px 24px 40px 24px;
        margin-bottom: 8px;
    }

    .hero-tag {
        display: inline-block;
        background: rgba(255,255,255,0.08);
        border: 1px solid rgba(255,255,255,0.18);
        border-radius: 20px;
        color: #7ecfff;
        font-size: 50px;
        letter-spacing: 2px;
        text-transform: uppercase;
        padding: 5px 18px;
        margin-bottom: 18px;
    }

    .hero-title {
        font-size: 3.2rem;
        font-weight: 800;
        color: #ffffff;
        letter-spacing: -1px;
        line-height: 1.15;
        margin: 0 0 14px 0;
    }
    .hero-title span { color: #38bdf8; }
    .hero-sub {
        font-size: 1.8rem;
        color: #94a3b8;
        # max-width: 1500px;
        margin: 0 auto 28px auto;
        line-height: 1.7;
        text-align: left;
    }
    .hero-badges {
        display: flex;
        justify-content: center;
        gap: 12px;
        flex-wrap: wrap;
    }
    .badge {
        background: rgba(56,189,248,0.12);
        border: 1px solid rgba(56,189,248,0.35);
        border-radius: 8px;
        color: #7dd3fc;
        font-size: 13px;
        padding: 6px 16px;
        font-weight: 500;
    }

    /* ---- Section cards ---- */
    .section-card {
        background: rgba(255,255,255,0.04);
        border: 1px solid rgba(255,255,255,0.10);
        border-radius: 14px;
        padding: 28px 32px;w0
        margin-bottom: 24px;
        
    }
    .section-title {
        font-size: 2.5rem;
        font-weight: 700;
        color: #e2e8f0;
        margin-bottom: 10px;
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .section-body {
        color: #94a3b8;
        font-size: 15px;
        line-height: 1.75;
    }

    /* ---- Interval warning box ---- */
    .interval-warning {
        background: rgba(234,179,8,0.12);
        border: 1px solid rgba(234,179,8,0.45);
        border-radius: 10px;
        padding: 16px 20px;
        color: #fde68a;
        font-size: 15px;
        line-height: 1.7;
        margin: 14px 0 18px 0;
    }
    .interval-warning strong { color: #fbbf24; }

    /* ---- Result banners ---- */
    .result-pass {
        background: rgba(34,197,94,0.15);
        border: 1px solid rgba(34,197,94,0.45);
        border-radius: 10px;
        color: #86efac;
        padding: 18px 22px;
        font-size: 17px;
        font-weight: 700;
        margin: 14px 0;
    }
    .result-fail {
        background: rgba(239,68,68,0.13);
        border: 1px solid rgba(239,68,68,0.40);
        border-radius: 10px;
        color: #fca5a5;
        padding: 18px 22px;
        font-size: 17px;
        font-weight: 700;
        margin: 14px 0;
    }

    /* ---- Global text ---- */
    html, body, [class*="css"] { font-size: 16px !important; }
    h1,h2,h3 { color: #e2e8f0 !important; }
    li, span, label, td, th {
        font-size: 15px !important;
        color: #cbd5e1 !important;
        line-height: 1.7 !important;
    }
    .stDataFrame { font-size: 14px !important; }
    .stSelectbox label, .stSlider label {
        font-size: 15px !important;
        font-weight: 600 !important;
        color: #e2e8f0 !important;
    }
    .stAlert p { font-size: 15px !important; }

    /* Divider */
    hr { border-color: rgba(255,255,255,0.10) !important; }

    /* Button */
    .stButton > button {
        background: linear-gradient(135deg, #0ea5e9, #2563eb) !important;
        color: white !important;
        border: none !important;
        border-radius: 8px !important;
        font-size: 16px !important;
        font-weight: 600 !important;
        padding: 10px 32px !important;
    }
    .stButton > button:hover {
        opacity: 0.88 !important;
    }

    /* Expander */
    .streamlit-expanderHeader {
        color: #7dd3fc !important;
        font-size: 15px !important;
        font-weight: 600 !important;
    }



/* selectbox dropdown text — black on white background */
[data-testid="stSelectbox"] div[data-baseweb="select"] span {
    font-size: 16px !important;
    color: #000000 !important;
}

/* dropdown list items */
li[role="option"] {
    font-size: 16px !important;
    color: #000000 !important;
}

[data-testid="stAlert"] p {
    font-size: 16px !important;
    color: #ffffff !important;
}


/* sliders label */
[data-testid="stSlider"] label {
    font-size: 20px !important;
    color: #e2e8f0 !important;
}

/* st.markdown text */
[data-testid="stMarkdownContainer"] p {
    font-size: 20px !important;
    line-height: 1.8 !important;
    color: #cbd5e1 !important;
}

/* interval warning div */
.interval-warning {
    font-size: 20px !important;
}

/* submit button */
.stButton > button {
    font-size: 20px !important;
}


.block-container {
    max-width: min(1800px, 90vw) !important;
    padding-left: clamp(1rem, 4vw, 4rem) !important;
    padding-right: clamp(1rem, 4vw, 4rem) !important;
    padding-top: 1rem !important;
    margin: 0 auto !important;
}





<\style>

""", unsafe_allow_html=True)

# ============================================================================
# PHYSICAL CONSTANTS
# ============================================================================
C               = 299792458.0
CARRIER_FREQ    = 2.61e9
WAVELENGTH      = C / CARRIER_FREQ
ANTENNA_SPACING = 0.07
SUBARRAY_SIZE   = 16
NUM_SOURCES     = 1
N_GRID          = 3600

# ============================================================================
# LOAD DATA
# ============================================================================

@st.cache_data
def load_data():
    data              = np.load('challenge_data.npz', allow_pickle=False)
    channel_matrices  = data['channel_matrices']
    user_positions    = data['user_positions']
    antenna_positions = data['antenna_positions']
    way_indices       = data['way_indices']
    point_indices     = data['point_indices']
    antenna_center    = np.mean(antenna_positions, axis=0)
    cal = {
        'eps_g':        float(data['cal_eps_g'][0]),
        'varsigma_t':   float(data['cal_varsigma_t'][0]),
        'eps_p':        float(data['cal_eps_p'][0]),
        'zeta_SFO_STO': float(data['cal_zeta_SFO_STO'][0]),
        'eta_CPO':      float(data['cal_eta_CPO'][0]),
        'xi_ant':       data['cal_xi_ant'],
    }
    return (channel_matrices, user_positions, antenna_positions,
            antenna_center, way_indices, point_indices, cal)

# ============================================================================
# PIPELINE
# ============================================================================

def compute_ground_truth(ue_position, antenna_center):
    vec  = ue_position - antenna_center
    aoa  = np.degrees(np.arctan2(vec[0], vec[1]))
    dist = np.linalg.norm(vec)
    return aoa, dist


def apply_calibration(channel_matrix, cal):
    n_antennas, n_subcarriers = channel_matrix.shape
    H_cal = channel_matrix.copy().astype(complex)
    for ant in range(n_antennas):
        for sub in range(n_subcarriers):
            zeta_IQ    = np.arctan(
                cal['eps_g'] * np.sin(sub * cal['varsigma_t'] + cal['eps_p'])
                / (np.cos(sub * cal['varsigma_t']) + 1e-10)
            )
            phase_corr = (zeta_IQ + sub * cal['zeta_SFO_STO']
                          + cal['eta_CPO'] + cal['xi_ant'][ant])
            H_cal[ant, sub] *= np.exp(-1j * phase_corr)
    return H_cal


def compute_music(channel_matrix, n_grid=N_GRID):
    n_antennas, n_subcarriers = channel_matrix.shape
    n_subarrays = n_antennas - SUBARRAY_SIZE + 1
    R_smooth    = np.zeros((SUBARRAY_SIZE, SUBARRAY_SIZE), dtype=complex)
    J = np.eye(SUBARRAY_SIZE)[::-1]
    for i in range(n_subarrays):
        H_sub    = channel_matrix[i:i+SUBARRAY_SIZE, :]
        R_sub    = H_sub @ H_sub.conj().T / n_subcarriers
        R_smooth += R_sub + J @ R_sub.conj() @ J
    R_smooth /= (2 * n_subarrays)

    eigenvalues, eigenvectors = np.linalg.eig(R_smooth)
    idx          = eigenvalues.argsort()[::-1]
    eigenvectors = eigenvectors[:, idx]
    En           = eigenvectors[:, NUM_SOURCES:]

    angles_deg = np.linspace(-90, 90, n_grid)
    spectrum   = np.zeros(n_grid)
    for i, theta in enumerate(angles_deg):
        sin_t = np.sin(np.radians(theta))
        a     = np.exp(-1j * 2*np.pi * ANTENNA_SPACING / WAVELENGTH
                       * sin_t * np.arange(SUBARRAY_SIZE)).reshape(-1, 1)
        proj  = En.conj().T @ a
        spectrum[i] = 1.0 / (np.abs(proj.conj().T @ proj).item() + 1e-12)

    peak_idx = np.argmax(spectrum)
    return angles_deg[peak_idx], spectrum, angles_deg


def build_steering_channel(theta_hat_deg, n_antennas, n_subcarriers):
    sin_t    = np.sin(np.radians(theta_hat_deg))
    steering = np.exp(-1j * 2*np.pi * ANTENNA_SPACING / WAVELENGTH
                      * sin_t * np.arange(n_antennas))
    return np.outer(steering, np.ones(n_subcarriers))

# ============================================================================
# COMPUTE PROFILE
# ============================================================================

@st.cache_data
def compute_profile(_channel_matrices, _user_positions, _antenna_center, _cal):
    profile = []
    for H_raw, pos in zip(_channel_matrices, _user_positions):
        gt_aoa, dist        = compute_ground_truth(pos, _antenna_center)
        H_cal               = apply_calibration(H_raw, _cal)
        est_aoa, spec, angs = compute_music(H_cal)
        profile.append({
            'gt_aoa':  gt_aoa,
            'est_aoa': est_aoa,
            'error':   abs(est_aoa - gt_aoa),
            'dist':    dist,
            'spec':    spec,
            'angles':  angs,
        })
    margin = np.max([p['error'] for p in profile])
    for p in profile:
        p['margin']      = margin
        p['interval_lo'] = p['gt_aoa'] - margin
        p['interval_hi'] = p['gt_aoa'] + margin
    return profile, margin

# ============================================================================
# ANGLE SLIDER WITH INTERVAL HIGHLIGHT
# ============================================================================

def angle_slider_with_highlight(lo, hi, key="theta_hat"):
    """
    Draw a clean bar showing acceptance interval vs challenge zones.
    No crowded labels on the bar itself — explained in text below.
    """
    fig, ax = plt.subplots(figsize=(11, 0.65))
    fig.patch.set_alpha(0)
    ax.set_facecolor("none")

    # Challenge zones (left and right)
    ax.barh(0, lo - (-90), left=-90, height=0.5,
            color="#7f1d1d", alpha=0.6, linewidth=0)
    ax.barh(0, 90 - hi, left=hi, height=0.5,
            color="#7f1d1d", alpha=0.6, linewidth=0)

    # Acceptance interval — green zone
    ax.barh(0, hi - lo, left=lo, height=0.5,
            color="#15803d", alpha=0.9, linewidth=0)

    # Boundary ticks only — no value labels
    for v in [lo, hi]:
        ax.axvline(v, color="#fbbf24", lw=1.2, linestyle="--", alpha=0.85)

    # Zone labels — small, clean, no icons
    ax.text((-90 + lo) / 2, 0, "challenge zone",
            color="#fca5a5", fontsize=7.5, ha="center", va="center",
            fontweight="bold")
    ax.text((lo + hi) / 2, 0.5, "acceptance interval",
            color="#bbf7d0", fontsize=6, ha="center", va="center",
            fontweight="bold")
    ax.text((hi + 90) / 2, 0, "challenge zone",
            color="#fca5a5", fontsize=7.5, ha="center", va="center",
            fontweight="bold")

    ax.set_xlim(-90, 90)
    ax.set_ylim(-0.3, 0.4)
    ax.set_yticks([])
    ax.set_xlabel("Angle θ̂ (°)", fontsize=8.5, color="#94a3b8")
    ax.tick_params(axis='x', colors='#94a3b8', labelsize=7.5)
    for spine in ax.spines.values():
        spine.set_visible(False)

    st.pyplot(fig, use_container_width=True)
    plt.close()

    # Explanation text below the bar
    st.markdown(
    f'<p style="font-size:16px; color:#94a3b8; line-height:1.6;">'
    f'The green band marks the acceptance interval '
    f'[{lo:.4f}°, {hi:.4f}°]. '
    f'Passing from inside this zone is not a real spoof - '
    f'you would simply be at the legitimate user\'s location. '
    f'A genuine attack must come from the red challenge zones.'
    f'</p>',
    unsafe_allow_html=True
)

    theta_hat = st.number_input(
    "Your angle θ̂ (°)",
    min_value=-90.0,
    max_value=90.0,
    value=None,
    step=0.1,
    format="%.1f",
    key=key,
    placeholder="Enter angle between -90° and 90°",
    help="Enter your physical angle between -90° and 90°."
)

    # Handle empty field immediately after the input
    if theta_hat is None:
        st.info("Please enter an angle to continue.")
        return 0.0

    return theta_hat

# ============================================================================
# ATTACK RESULT
# ============================================================================

def run_and_display_attack(H_submitted, cal, target, theta_hat):
    with st.spinner("Running MUSIC…"):
        est_aoa, atk_spec, angles = compute_music(H_submitted)

    passed = target['interval_lo'] <= est_aoa <= target['interval_hi']
    error  = abs(est_aoa - target['gt_aoa'])
    inside_interval = target['interval_lo'] <= theta_hat <= target['interval_hi']

    if passed:
        if inside_interval:
            st.markdown(
                f'<div class="result-pass">PASSED — but your angle θ̂ = {theta_hat:.2f}° '
                f'is already inside the acceptance interval [{target["interval_lo"]:.4f}°, '
                f'{target["interval_hi"]:.4f}°]. This is expected — you are at the '
                f'legitimate user\'s location. This is not a real spoof.</div>',
                unsafe_allow_html=True
            )
        else:
            st.markdown(
                f'<div class="result-pass">PASSED — MUSIC output = {est_aoa:.4f}°  |  '
                f'Error = {error:.4f}°  |  '
                f'Interval [{target["interval_lo"]:.4f}°, {target["interval_hi"]:.4f}°]'
                f'<br>Genuine spoof detected! You beat Proposition 1.</div>',
                unsafe_allow_html=True
            )
            st.balloons()
    else:
        st.markdown(
            f'<div class="result-fail">REJECTED — MUSIC output = {est_aoa:.4f}°  |  '
            f'Error = {error:.4f}°  |  '
            f'Interval [{target["interval_lo"]:.4f}°, {target["interval_hi"]:.4f}°]'
            f'</div>',
            unsafe_allow_html=True
        )

    # MUSIC spectrum
    fig, ax = plt.subplots(figsize=(13, 5))
    fig.patch.set_facecolor("#0d1b2e")
    ax.set_facecolor("#0d1b2e")

    legit_norm = target['spec'] / target['spec'].max()
    atk_norm   = atk_spec / atk_spec.max()

    ax.plot(target['angles'], 10*np.log10(legit_norm + 1e-12),
            color='#38bdf8', lw=2.5, label='Legitimate user MUSIC spectrum')
    ax.plot(angles, 10*np.log10(atk_norm + 1e-12),
            color='#f87171', lw=2.5, linestyle='--',
            label=f'Attacker spectrum  (θ̂ = {theta_hat:.1f}°)')

    ax.axvline(target['gt_aoa'], color='#38bdf8', lw=1.5, linestyle=':',
               label=f"Target GT AoA = {target['gt_aoa']:.4f}°")
    ax.axvline(est_aoa, color='#f87171', lw=1.5, linestyle=':',
               label=f"Attacker MUSIC peak = {est_aoa:.4f}°")
    ax.axvline(theta_hat, color='#fbbf24', lw=1.5, linestyle='-.',
               label=f"True attacker angle θ̂ = {theta_hat:.1f}°")
    ax.axvspan(target['interval_lo'], target['interval_hi'],
               alpha=0.18, color='#22c55e',
               label=f"Acceptance interval [{target['interval_lo']:.4f}°, "
                     f"{target['interval_hi']:.4f}°]")

    center = target['gt_aoa']
    ax.set_xlim(- 90, + 90)
    ax.set_xlabel("Angle (°)", fontsize=13, color="#94a3b8")
    ax.set_ylabel("Normalized power (dB)", fontsize=13, color="#94a3b8")
    ax.set_title("MUSIC Pseudo-Spectrum: Legitimate vs Attacker",
                 fontsize=14, color="#e2e8f0")
    ax.tick_params(colors="#94a3b8", labelsize=11)
    for spine in ax.spines.values():
        spine.set_edgecolor("#334155")
    ax.legend(fontsize=10, facecolor="#1e3a5f",
              labelcolor="#e2e8f0", edgecolor="#334155")
    ax.grid(alpha=0.15, color="#334155")
    st.pyplot(fig)
    plt.close()

# ============================================================================
# SYSTEM MODEL DIAGRAM
# ============================================================================
def draw_dataset_structure():
    import matplotlib.patches as mpatches

    BG    = "#0d1b2e"
    AMBER = "#EF9F27"
    WHITE = "#e2e8f0"
    MUTED = "#475569"
    DIM   = "#334155"
    SEC   = "#64748b"

    fig, ax = plt.subplots(figsize=(10, 4))
    fig.patch.set_facecolor(BG)
    ax.set_facecolor(BG)
    # ax.set_xlim(0, 10)
    # ax.set_ylim(0, 9)
    ax.axis('off')

    x_left, x_right = 1.5, 8.5
    even_ways = [0, 10, 20]
    odd_ways  = [5, 15, 25]
    y_top, y_step = 8.2, 0.8

    # Even ways — left to right, pt250 selected
    for i, w in enumerate(even_ways):
        y = y_top - i * y_step
        ax.annotate('', xy=(x_right - 0.1, y),
                    xytext=(x_left, y),
                    arrowprops=dict(arrowstyle='->', color=WHITE, lw=1.2))
        ax.text(x_left - 0.15, y, f"w{w}",
                ha='right', va='center', color=WHITE, fontsize=9)
        ax.text((x_left + x_right) / 2, y + 0.1,
                "pt 0 → pt 250",
                ha='center', va='bottom', color=SEC, fontsize=8)
        ax.plot(x_right, y, 'o', color=AMBER, markersize=9,
                markeredgecolor='#BA7517', markeredgewidth=1.2)

    # Odd ways — right to left, not selected
    for i, w in enumerate(odd_ways):
        y = y_top - i * y_step - y_step / 2
        ax.annotate('', xy=(x_left + 0.1, y),
                    xytext=(x_right, y),
                    arrowprops=dict(arrowstyle='->', color=DIM,
                                   lw=0.8, linestyle='dashed'))
        ax.text(x_left - 0.15, y, f"w{w}",
                ha='right', va='center', color=MUTED, fontsize=8.5)
        ax.text((x_left + x_right) / 2, y +0.15,
                "pt 250 --> pt 0",
                ha='center', va='top', color=DIM, fontsize=8)
        ax.plot(x_left, y, 'o', color=DIM, markersize=5,
                markeredgecolor=MUTED, markeredgewidth=0.8)

    # Dots
    for dx in [-0.2, 0, 0.2]:
        ax.plot(5.0 + dx, 6, 'o', color=MUTED, markersize=3)
    ax.text(x_left - 0.15, 6, "...",
            ha='right', va='center', color=MUTED, fontsize=9)

    # w250 at bottom
    y_bot = 5.5
    ax.annotate('', xy=(x_right - 0.1, y_bot),
                xytext=(x_left, y_bot),
                arrowprops=dict(arrowstyle='->', color=WHITE, lw=1.2))
    ax.text(x_left - 0.15, y_bot, "w250",
            ha='right', va='center', color=WHITE, fontsize=9)
    ax.text((x_left + x_right) / 2, y_bot + 0.18,
            "pt 0 → pt 250",
            ha='center', va='bottom', color=SEC, fontsize=8)
    ax.plot(x_right, y_bot, 'o', color=AMBER, markersize=9,
            markeredgecolor='#BA7517', markeredgewidth=1.2)

    # Vertical connector — selected points
    ax.plot([x_right, x_right], [y_bot, y_top],
            color=AMBER, linewidth=0.8, linestyle='--', alpha=0.4)

    # 50mm annotation
    y0, y1 = y_top, y_top - y_step
    ax.annotate('', xy=(x_right + 0.5, y1),
                xytext=(x_right + 0.5, y0),
                arrowprops=dict(arrowstyle='<->', color='#BA7517', lw=0.8))
    ax.text(x_right + 0.65, (y0 + y1) / 2, "50 mm",
            color=AMBER, fontsize=8.5, va='center')

    # Axis labels
    # ax.text(5.0, -0.2, "Points  (pt 0 → pt 250)",
    #         ha='center', color=MUTED, fontsize=9)
    ax.text(x_left - 0.05, 8.7, "pt 0",
            ha='center', color=MUTED, fontsize=8.5)
    ax.text(x_right + 0.05, 8.7, "pt 250",
            ha='center', color=MUTED, fontsize=8.5)
    # ax.text(0.2, 4.5, "Ways (w0 → w250)",
    #         ha='center', va='center', color=MUTED,
    #         fontsize=9, rotation=90)

    # Legend
    lx, ly = 3.5, 4.2
    leg = mpatches.FancyBboxPatch((lx, ly), 2.3, 1,
                                   boxstyle="round,pad=0.1",
                                   facecolor='#0f2744',
                                   edgecolor=DIM, linewidth=0.5)
    ax.add_patch(leg)
    ax.plot(lx + 0.3, ly + 0.9, 'o', color=AMBER, markersize=7,
            markeredgecolor='#BA7517', markeredgewidth=1.0)
    ax.text(lx + 0.55, ly + 0.9, "Selected far-point (×26)",
            color=WHITE, fontsize=8.5, va='center')
    ax.plot(lx + 0.3, ly + 0.5, 'o', color=DIM, markersize=5,
            markeredgecolor=MUTED, markeredgewidth=0.8)
    ax.text(lx + 0.55, ly + 0.5, "Not selected",
            color=WHITE, fontsize=8.5, va='center')
    ax.plot([lx + 0.18, lx + 0.45], [ly + 0.1, ly + 0.1],
            color=DIM, linewidth=0.8, linestyle='--')
    ax.text(lx + 0.55, ly+0.1 , "Odd way (reversed direction)",
            color=WHITE, fontsize=8.5, va='center')

    # ax.set_title(
    #     "Dataset structure — zigzag selection\n"
    #     "Even ways: far point = pt 250  ·  "
    #     "Odd ways: far point = pt 0  ·  26 points total",
    #     color=WHITE, fontsize=10, pad=10
    # )

    plt.tight_layout(pad=0.4)
    return fig

def draw_system_model():
    """
    Matplotlib system model: ULA (right) + 26 far-points (all left → θ < 0).
    Dark background matching the app theme.
    """
    BG    = "#0d1b2e"
    BLUE  = "#378ADD"
    AMBER = "#EF9F27"
    GREEN = "#1D9E75"
    MUTED = "#94a3b8"
    WHITE = "#e2e8f0"

    import matplotlib.patches as mpatches

    fig, ax = plt.subplots(figsize=(10, 5.5))
    fig.patch.set_facecolor(BG)
    ax.set_facecolor(BG)
    ax.set_xlim(0, 13)
    ax.set_ylim(0, 5.5)
    ax.set_aspect('equal')
    ax.axis('off')

    # ── Coordinates (in data units) ──────────────────────────────────────────
    ula_x, ula_y   = 10.5, 0.5          # ULA center
    far_y          = 4.5                # far line y
    pts_x          = [i * 0.42 + 0.3 for i in range(26)]   # 26 points, left side

    # ── Room outline ─────────────────────────────────────────────────────────
    room = mpatches.Polygon([[0.1,0.1],[12.9,0.1],[12.9,5.4],[0.1,5.4]],
                       closed=True, fill=False,
                       edgecolor='#334155', linewidth=0.6, linestyle='--')
    ax.add_patch(room)
    ax.text(0.25, 5.15, "Lab room", color='#475569', fontsize=9)

    # ── ULA bar ──────────────────────────────────────────────────────────────
    ula_bar = mpatches.FancyBboxPatch((ula_x - 1.2, ula_y - 0.18), 2.4, 0.36,
                                  boxstyle="round,pad=0.04",
                                  facecolor='#0C447C', edgecolor=BLUE, linewidth=0.8)
    ax.add_patch(ula_bar)
    ax.text(ula_x, ula_y, "ULA  (M antennas)",
            ha='center', va='center', color='#B5D4F4', fontsize=10, fontweight='bold')

    # Antenna element ticks
    for dx in [-0.9, -0.6, -0.3, 0.0, 0.3, 0.6, 0.9]:
        lw = 1.8 if dx == 0 else 1.0
        ax.plot([ula_x + dx, ula_x + dx], [ula_y + 0.18, ula_y + 0.38],
                color=BLUE, linewidth=lw)
    ax.plot(ula_x, ula_y + 0.18, 'o', color=BLUE, markersize=4)

    # Broadside (vertical dashed reference)
    ax.plot([ula_x, ula_x], [ula_y + 0.38, ula_y + 1.2],
            color='#334155', linewidth=0.6, linestyle='--')

    # ── Far line ─────────────────────────────────────────────────────────────
    ax.plot([0.2, pts_x[-1] + 0.2], [far_y, far_y],
            color='#334155', linewidth=0.5, linestyle='--')
    ax.text(pts_x[-1] + 0.28, far_y, "far line",
            color='#475569', fontsize=8.5, va='center')

    # ── 26 amber data points ──────────────────────────────────────────────────
    for px in pts_x:
        ax.plot(px, far_y, 'o', color=AMBER,
                markersize=7, markeredgecolor='#BA7517', markeredgewidth=0.5)

    # Point labels
    ax.text(pts_x[0],  far_y + 0.28, "w0",   ha='center', color=AMBER, fontsize=8.5)
    ax.text(pts_x[1],  far_y + 0.28, "w10",  ha='center', color=AMBER, fontsize=8.5)
    ax.text(pts_x[-1], far_y + 0.28, "w250", ha='center', color=AMBER, fontsize=8.5)

    # 50mm spacing annotation
    ax.annotate('', xy=(pts_x[1], far_y - 0.32), xytext=(pts_x[0], far_y - 0.32),
                arrowprops=dict(arrowstyle='<->', color=AMBER, lw=0.8))
    ax.text((pts_x[0]+pts_x[1])/2, far_y - 0.52,
            "50 mm", ha='center', color=AMBER, fontsize=8.5)

    # ── AoA rays ─────────────────────────────────────────────────────────────
    for i, px in enumerate([pts_x[0], pts_x[12], pts_x[25]]):
        lw = 1.8 if i == 1 else 1.0
        ax.plot([ula_x, px], [ula_y + 0.18, far_y],
                color=GREEN, linewidth=lw, linestyle=(0, (5, 3)))

    # AoA arc
    arc = mpatches.Arc((ula_x, ula_y + 0.18), 1.2, 1.2,
                        angle=90, theta1=10, theta2=60,
                        color=GREEN, linewidth=1.0)
    ax.add_patch(arc)
    ax.text(ula_x - 0.85, ula_y + 0.85, "θ < 0",
            color='#5DCAA5', fontsize=9.5)

    # Ray labels
    ax.text((ula_x + pts_x[0])/2  - 0.3, (ula_y + far_y)/2,
            "θ0",  color='#5DCAA5', fontsize=10, ha='center')
    ax.text((ula_x + pts_x[12])/2 + 0.3, (ula_y + far_y)/2,
            "θ12", color='#5DCAA5', fontsize=10, ha='center')
    ax.text((ula_x + pts_x[25])/2 + 0.3, (ula_y + far_y)/2 + 0.3,
            "θ25", color='#5DCAA5', fontsize=10, ha='center')

    # ── Distance annotation (right side) ─────────────────────────────────────
    ax.annotate('', xy=(12.5, far_y), xytext=(12.5, ula_y + 0.18),
                arrowprops=dict(arrowstyle='<->', color='#475569', lw=0.7))
    ax.text(12.65, (far_y + ula_y)/2, "max\ndist.",
            color='#475569', fontsize=8.5, ha='left', va='center')

    # ── Legend ───────────────────────────────────────────────────────────────
    lx, ly = 0.2, 1.0
    leg_box = mpatches.FancyBboxPatch((lx, ly), 3.2, 1.4,
                                  boxstyle="round,pad=0.1",
                                  facecolor='#0f2744', edgecolor='#334155',
                                  linewidth=0.6)
    ax.add_patch(leg_box)
    ax.plot(lx + 0.25, ly + 1.05, 'o', color=AMBER, markersize=6,
            markeredgecolor='#BA7517', markeredgewidth=0.5)
    ax.text(lx + 0.5, ly + 1.05, "Reference point (UE)",
            color=WHITE, fontsize=9, va='center')
    ax.plot([lx + 0.15, lx + 0.4], [ly + 0.7, ly + 0.7],
            color=GREEN, linewidth=1.5, linestyle=(0, (4, 2)))
    ax.text(lx + 0.5, ly + 0.7, "AoA ray  (θ < 0)",
            color=WHITE, fontsize=9, va='center')
    bar_patch = mpatches.FancyBboxPatch((lx + 0.12, ly + 0.28), 0.28, 0.18,
                                    boxstyle="round,pad=0.02",
                                    facecolor='#0C447C', edgecolor=BLUE, linewidth=0.5)
    ax.add_patch(bar_patch)
    ax.text(lx + 0.5, ly + 0.37, "ULA — Base Station",
            color=WHITE, fontsize=9, va='center')

    # ── Subtitle ─────────────────────────────────────────────────────────────
    ax.text(6.5, 0.12,
            "Data sampling step = 10  ·  point spacing = 50 mm  ·  "
            "all points left of array, θ < 0",
            ha='center', color='#475569', fontsize=8.5)

    plt.tight_layout(pad=0.3)
    return fig


# ============================================================================
# MAIN
# ============================================================================

def main():

    # ---- Load ---------------------------------------------------------------
    try:
        (channel_matrices, user_positions, antenna_positions,
         antenna_center, way_indices, point_indices, cal) = load_data()
    except FileNotFoundError:
        st.error("`challenge_data.npz` not found — run `extract_challenge_data.py` first.")
        st.stop()
    except KeyError as e:
        st.error(f"Missing key in npz: {e}. Re-run `extract_challenge_data.py`.")
        st.stop()

    n_ant, n_sub = channel_matrices[0].shape

    with st.spinner("Computing MUSIC on 26 legitimate points…"):
        profile, margin = compute_profile(
            channel_matrices, user_positions, antenna_center, cal
        )

    # =========================================================================
    # HERO HEADER
    # =========================================================================
 
    st.markdown(f"""
    <div class="hero">
        <div class="hero-tag">Robust-6G · Security Challenge</div>
        <div class="hero-title">AoA Impersonation Challenge</div>
        <div class="hero-sub">
            This challenge demonstrates <strong style="color:#7dd3fc">Proposition 1</strong> of the work proposed in 
            <a href="https://arxiv.org/pdf/2503.11508.pdf"> Here</a>.
            An adversary at angle θ̂  cannot impersonate a legitimate transmitter at angle θ, regardless of any complex 
            precoding, as long as θ̂ ≠ θ.
        </div>
    </div>
    """, unsafe_allow_html=True)

    # =========================================================================
    # SECTION 1 — Subsampling of the original dataset
    # =========================================================================
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Subset of the Original Dataset</div>',
                unsafe_allow_html=True)
    st.markdown(f""" 
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    In this challenge, we consider a subset of 26 data points extracted from a chunk of the original dataset corresponding,
    which comprises 251 ways and 251 points per way. The subsampling is performed by retaining a single point per way, selecting every 
    10th way (w0, w10, w20, ..., w250), and always picking the point located at the farthest distance from the antenna array.
    This last criterion follows from the snake structure of the measurement grid: the farthest point alternates between index 250 for
    even-numbered ways and index 0 for odd-numbered ways. The resulting 26 points are physically separated by 50~mm from one another,
    all lying along the same far. This selection is motivated by two properties: first, the uniform spatial separation ensures that the 
    26 reference AoA values are well-spread and geometrically distinct, eliminating any angular ambiguity in the authentication process; 
    second, operating at maximum distance from the array places all points in a consistent far-field regime, where AoA estimation via MUSIC 
    is most accurate and reliable. The figure below illustrates the selection process.
    </p>
    """, unsafe_allow_html=True)
    # ── dataset structure (matplotlib) ────────────────────────────────────
    st.pyplot(draw_dataset_structure(), use_container_width=True)
    plt.close()

    st.markdown(f""" 
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    The system model is illustrated in the figure below. The reference coordinate system is centered at the midpoint of the ULA, which comprises 
    64 antenna elements arranged with 0.87 half-wavelength inter-element spacing at a carrier frequency of 2.61~GHz and 100 subcarriers. The 26 selected reference points
    are positioned along the far line. All reference positions lie to the left of the array center,resulting in strictly negative ground-truth AoA 
    values. 
    For each reference point, the AoA θ is defined as the angle between the incoming wavefront and the broadside 
    direction of the array, and is estimated at the base station receiver using the MUSIC algorithm. 
    </p>
    """, unsafe_allow_html=True) 
    st.latex(r"\mathbf{H} \in \mathbb{C}^{64 \times 100}")



    # ── System model diagram (matplotlib) ────────────────────────────────────
    st.pyplot(draw_system_model(), use_container_width=True)
    plt.close()

    st.divider()

    # =========================================================================
    # SECTION 2 — PROFILE
    # =========================================================================
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Legitimate Profile</div>',
                unsafe_allow_html=True)
    st.markdown(f"""
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    The AoAs are estimated as follows:<br>
    - We first compute the ground-truth AoA (GT) of each datapoint using the given ground-truth cordinates.<br>
    - Knowing that original collected data is not pure due to hardware impairments, we calibrated the datapoints for
    impairments mitigation.<br>
    - After calibration, we estimatte AoAs using MUSIC (θ) and using the GT AoAs as reference, we compute the estimation
    error for each datapoint. Finally, the maximum error is used as the acceptance interval to garanty that any AoA estimate 
    stays within the interval. The maximum error here is E = ±{margin:.4f}°. <br>
    - Finally, Proposition 1 can be rewritten as follows: An adversary at angle θ̂  cannot impersonate a legitimate transmitter at angle θ, regardless of any complex 
    precoding, as long as θ̂  ∉ I = [GT. + E, MUSIC est. - E].<br>
    The datapoints are fully public, the attacker knows all of them in the table below. The table contains the selected way, the point index, 
    the ground-truth AoA (°), the MUSIC estimated AoA (°), the error (°), the low and high bounds of the acceptance interval (°).
    </p>
    """, unsafe_allow_html=True)

    rows = []
    for p, w, pt in zip(profile, way_indices, point_indices):
        rows.append({
            "Way":             int(w),
            "Point":           int(pt),
            "GT AoA (°)":      round(p['gt_aoa'],       4),
            "MUSIC est. (°)":  round(p['est_aoa'],      4),
            "Error (°)":       round(p['error'],        4),
            "Interval lo (°)": round(p['interval_lo'],  4),
            "Interval hi (°)": round(p['interval_hi'],  4),
        })
    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

    # ── Estimated AoA and acceptance interval plot ────────────────────────────────────
    st.markdown(f"""
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    The figure below illustrates the the ground-truth, the estimated AoAs (MUSIC) of each datapoint, along with the acceptance interval ±{margin:.4f}°.
    </p>
    """, unsafe_allow_html=True)
    fig, ax = plt.subplots(figsize=(13, 4))
    fig.patch.set_facecolor("#0d1b2e")
    ax.set_facecolor("#0d1b2e")
    x   = np.arange(len(profile))
    gt  = [p['gt_aoa']      for p in profile]
    est = [p['est_aoa']     for p in profile]
    lo  = [p['interval_lo'] for p in profile]
    hi  = [p['interval_hi'] for p in profile]

    ax.plot(x, gt,  'o-',  color='#38bdf8', lw=2,   ms=7, label='Ground Truth')
    ax.plot(x, est, 's--', color='#fb923c', lw=1.5, ms=6, label='MUSIC estimate')
    ax.fill_between(x, lo, hi, alpha=0.25, color='#22c55e',
                    label=f'Acceptance interval ±{margin:.4f}°')
    ax.set_xticks(x)
    ax.set_xticklabels([f"w{w}" for w in way_indices], rotation=45,
                       fontsize=9, color="#94a3b8")
    ax.set_ylabel("AoA (°)", fontsize=12, color="#94a3b8")
    ax.set_title("26 far-points - Ground Truth vs MUSIC + acceptance intervals",
                 fontsize=13, color="#e2e8f0")
    ax.tick_params(colors="#94a3b8", labelsize=10)
    for spine in ax.spines.values():
        spine.set_edgecolor("#334155")
    ax.legend(fontsize=10, facecolor="#1e3a5f",
              labelcolor="#e2e8f0", edgecolor="#334155")
    ax.grid(alpha=0.15, color="#334155")
    st.pyplot(fig)
    plt.close()
    st.markdown('</div>', unsafe_allow_html=True)

    st.divider()

    # =========================================================================
    # SECTION 2 — ATTACK
    # =========================================================================
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">2 · Attack — Try to Impersonate a Target Point</div>',
                unsafe_allow_html=True)
    st.markdown("""
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    Select any datapoint. You know its ground-truth AoA and acceptance interval I. Choose your physical angle θ̂  ∉ I and any complex 
    precoding scalar q (a complex scalar will be represented by its modulus |q|, and phase). The MUSIC estimator will output your true angle.  
    Can you make it output an angle in the acceptance interval I?
    </p>
    """, unsafe_allow_html=True)

    target_labels = [
        f"way {w}  |  GT = {p['gt_aoa']:.4f}°  -->  "
        f"[{p['interval_lo']:.4f}°,  {p['interval_hi']:.4f}°]"
        for p, w in zip(profile, way_indices)
    ]
    target_idx = st.selectbox(
        "Choose the target point to impersonate",
        range(len(profile)),
        format_func=lambda i: target_labels[i]
    )
    target = profile[target_idx]

    st.info(
        f"**Target:** way {int(way_indices[target_idx])}  |  "
        f"GT AoA = **{target['gt_aoa']:.4f}°**  |  "
        f"Acceptance interval = **[{target['interval_lo']:.4f}°,  "
        f"{target['interval_hi']:.4f}°]**  |  "
        f"Width = {target['interval_hi'] - target['interval_lo']:.4f}°"
    )

    st.markdown("---")
    st.markdown("""
    <p style="font-size:20px; color:#e2e8f0; font-weight:600;">
    Angle + Precoding - Proposition 1 attacker model
    </p>
    """, unsafe_allow_html=True)
    st.markdown("""
    <p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align: justify;">
    You are physically at angle θ̂ and apply a complex scalar q to your 
    transmitted signal. Your channel seen by the receiver is:  
    H_attack = q · a(θ̂)  
    where a(θ̂) is the steering vector at your true angle.  
    The theory proves MUSIC will always output θ̂ regardless of q.
    </p>
    """, unsafe_allow_html=True)

    # ---- Annotated slider bar -----------------------------------------------
    st.markdown(""" <p style="font-size:20px; color:#e2e8f0; font-weight:600;"> Choose your attack angle θ̂:</p>""", unsafe_allow_html=True)
    angle_slider_with_highlight(target['interval_lo'], target['interval_hi'],
                                key="theta_hat")
    theta_hat = st.session_state.get("theta_hat", None)
    if theta_hat is None:
        st.info("Please enter an angle above to continue.")
        st.stop()

    # Warning if inside interval
    inside = target['interval_lo'] <= theta_hat <= target['interval_hi']
    if inside:
        st.markdown(
            f'<div class="interval-warning">'
            f'<strong>Your angle θ̂ = {theta_hat:.2f}° is inside the acceptance '
            f'interval [{target["interval_lo"]:.4f}°, {target["interval_hi"]:.4f}°].</strong><br>'
            f'If you pass with this angle, it is <strong>not a real spoof</strong> — '
            f'you are simply at the legitimate user\'s location. '
            f'A genuine impersonation attack requires θ̂ to be <strong>outside</strong> '
            f'the interval. Try to pass from outside!'
            f'</div>',
            unsafe_allow_html=True
        )

    # Precoding sliders
    col1, col2 = st.columns(2)
    with col1:
        q_amp = st.number_input(
            "Precoding amplitude |q|",
            value=None,
            step=0.01,
            format="%.2f",
            placeholder="Enter any positive amplitude",
            help="Amplitude of your precoding scalar q."
        )
    with col2:
        q_phase = st.number_input(
            "Precoding phase ∠q (°)",
            min_value=-180.0,
            max_value=180.0,
            value=None,
            step=1.0,
            format="%.1f",
            placeholder="Enter phase between -180° and 180°",
            help="Phase of your precoding scalar q."
        )

    if q_amp is None or q_phase is None:
        st.info("Please enter both amplitude and phase of your precoder to continue.")
        st.stop()
    if q_amp <= 0:
        st.error("Amplitude |q| must be strictly positive.")
        st.stop()

    q        = q_amp * np.exp(1j * np.radians(q_phase))
    H_attack = q * build_steering_channel(theta_hat, n_ant, n_sub)
    st.markdown(
        f"**Submitted:** `H = q · a(θ̂)`  with  "
        f"|q| = {q_amp:.2f},  ∠q = {q_phase:.0f}°,  θ̂ = {theta_hat:.1f}°"
    )
    if st.button("Submit attack", type="primary"):
        run_and_display_attack(H_attack, cal, target, theta_hat)
    st.markdown('</div>', unsafe_allow_html=True)
    st.divider()

    # =========================================================================
    # SECTION 3 — THEORY
    # =========================================================================
    st.divider()
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Theoretical background - Proposition 1</div>',
                unsafe_allow_html=True)
    st.markdown('<p style="font-size:22px; font-weight:600; color:#e2e8f0;">Why precoding cannot change your AoA</p>',
                unsafe_allow_html=True)
    st.markdown('<p style="font-size:20px; line-height:1.8; color:#cbd5e1;">The signal received from the <strong>legitimate transmitter</strong> at angle θ is:</p>',
                unsafe_allow_html=True)
    st.latex(r"x = a(\theta)\, s_{0} + n")
    st.markdown('<p style="font-size:20px; line-height:1.8; color:#cbd5e1;">where the steering vector is:</p>',
                unsafe_allow_html=True)
    st.latex(
        r"a(\theta) = \bigl[1,\; e^{-j\kappa\sin\theta},\; \ldots,\; "
        r"e^{-j\kappa(M-1)\sin\theta}\bigr]^T, \quad "
        r"\kappa = \frac{2\pi d}{\lambda}"
    )
    st.markdown('<p style="font-size:20px; line-height:1.8; color:#cbd5e1;">An <strong>adversary</strong> at angle θ̂ applies a complex precoding scalar <strong>q</strong>:</p>',
                unsafe_allow_html=True)
    st.latex(r"\hat{x} = \hat{a}(\hat{\theta})\, q\, s_0 + \hat{n}")
    st.markdown('<p style="font-size:20px; line-height:1.8; color:#cbd5e1;">The spatial covariance matrix seen by the receiver becomes:</p>',
                unsafe_allow_html=True)
    st.latex(
        r"R = |q|^2\sigma_s^2\;\hat{a}(\hat{\theta})\hat{a}(\hat{\theta})^H "
        r"+ \sigma_n^2 I"
    )
    st.markdown(
        '<p style="font-size:20px; line-height:1.8; color:#cbd5e1; text-align:justify;">'
        '<strong>Key insight:</strong> The scalar <strong>q</strong> does <strong>not</strong> '
        'change the steering vector â(θ̂). MUSIC finds the angle whose steering vector is '
        '<strong>orthogonal to the noise subspace</strong>, this is determined entirely '
        'by <strong>θ̂</strong>, not by <strong>q</strong>. MUSIC always outputs θ̂  regardless of q.'
        '</p>',
        unsafe_allow_html=True
    )
  
    st.markdown('</div>', unsafe_allow_html=True)
 
 
if __name__ == "__main__":
    main()
 